const monthIds = [
  "jan",
  "feb",
  "mar",
  "apr",
  "maj",
  "jun",
  "jul",
  "aug",
  "sep",
  "okt",
  "nov",
  "dec",
] as const;

function monthlyValues(values: number | readonly number[]): Record<string, number> {
  const amounts = typeof values === "number" ? monthIds.map(() => values) : values;
  return Object.fromEntries(monthIds.map((monthId, index) => [monthId, amounts[index]]));
}

export const currentPlanningYear = 2026;

export const seedPlanningDataV3 = {
  version: 3 as const,
  openingBalance: 68_400,
  incomes: [
    {
      id: "income-salary",
      name: "Inkomster",
      monthlyValues: monthlyValues(54_800),
      recurring: true,
    },
  ],
  expenseCategories: [
    { id: "boende", name: "Boende", order: 0 },
    { id: "bil", name: "Bil", order: 1 },
    { id: "mat", name: "Mat", order: 2 },
    { id: "streaming", name: "Streaming", order: 3 },
    { id: "forsakringar", name: "Försäkringar", order: 4 },
    { id: "husdjur", name: "Husdjur", order: 5 },
    { id: "sparande", name: "Sparande", order: 6 },
    { id: "lan-och-krediter", name: "Lån och krediter", order: 7 },
    { id: "ovrigt", name: "Övrigt", order: 8 },
  ],
  expenseItems: [
    {
      id: "boende-hyra",
      category: "boende",
      name: "Hyra",
      monthlyValues: monthlyValues(13_900),
      recurring: true,
    },
    {
      id: "boende-el",
      category: "boende",
      name: "El",
      monthlyValues: monthlyValues(1_450),
      recurring: true,
    },
    {
      id: "boende-internet",
      category: "boende",
      name: "Internet",
      monthlyValues: monthlyValues(1_050),
      recurring: true,
    },
    {
      id: "bil-billan",
      category: "bil",
      name: "Billån",
      monthlyValues: monthlyValues(3_850),
      recurring: true,
    },
    {
      id: "bil-forsakring",
      category: "bil",
      name: "Försäkring",
      monthlyValues: monthlyValues(1_250),
      recurring: true,
    },
    {
      id: "bil-service",
      category: "bil",
      name: "Service",
      monthlyValues: monthlyValues([1_100, 0, 0, 6_500, 0, 0, 3_300, 0, 0, 0, 0, 0]),
      recurring: true,
    },
    {
      id: "bil-bransle",
      category: "bil",
      name: "Bränsle",
      monthlyValues: monthlyValues([0, 0, 0, 2_200, 0, 0, 1_700, 0, 1_950, 0, 0, 0]),
      recurring: true,
    },
    {
      id: "mat-mat",
      category: "mat",
      name: "Mat",
      monthlyValues: monthlyValues([
        7_800,
        7_600,
        7_900,
        8_200,
        7_700,
        8_800,
        10_600,
        8_500,
        7_800,
        7_900,
        8_700,
        10_800,
      ]),
      recurring: true,
    },
    {
      id: "streaming-netflix",
      category: "streaming",
      name: "Netflix",
      monthlyValues: monthlyValues(179),
      recurring: true,
    },
    {
      id: "streaming-spotify",
      category: "streaming",
      name: "Spotify",
      monthlyValues: monthlyValues(119),
      recurring: true,
    },
    {
      id: "streaming-tv",
      category: "streaming",
      name: "TV",
      monthlyValues: monthlyValues(222),
      recurring: true,
    },
    {
      id: "forsakringar-forsakringar",
      category: "forsakringar",
      name: "Försäkringar",
      monthlyValues: monthlyValues(2_100),
      recurring: true,
    },
    {
      id: "husdjur-husdjur",
      category: "husdjur",
      name: "Husdjur",
      monthlyValues: monthlyValues([
        1_250,
        1_280,
        1_480,
        1_280,
        1_280,
        1_480,
        1_480,
        1_280,
        1_280,
        1_280,
        1_280,
        1_480,
      ]),
      recurring: true,
    },
    {
      id: "sparmal-buffert",
      category: "sparande",
      name: "Buffert",
      monthlyValues: monthlyValues([
        5_000,
        6_000,
        6_000,
        8_000,
        7_000,
        6_000,
        4_000,
        5_000,
        7_000,
        8_000,
        6_000,
        3_000,
      ]),
      recurring: true,
    },
    {
      id: "sparmal-pension",
      category: "sparande",
      name: "Pension",
      monthlyValues: monthlyValues(0),
      recurring: true,
    },
    {
      id: "sparmal-investeringar",
      category: "sparande",
      name: "Investeringar",
      monthlyValues: monthlyValues(0),
      recurring: true,
    },
    {
      id: "ovrigt-ovrigt",
      category: "ovrigt",
      name: "Övrigt",
      monthlyValues: monthlyValues([
        2_630,
        3_600,
        4_700,
        3_600,
        3_700,
        18_300,
        27_500,
        16_300,
        1_600,
        4_000,
        21_800,
        35_700,
      ]),
      recurring: true,
    },
  ],
};

export const emptyPlanningDataV3 = {
  ...seedPlanningDataV3,
  openingBalance: 0,
  incomes: seedPlanningDataV3.incomes.map((income) => ({
    ...income,
    monthlyValues: monthlyValues(0),
  })),
  expenseCategories: seedPlanningDataV3.expenseCategories.map((category) => ({
    ...category,
  })),
  expenseItems: seedPlanningDataV3.expenseItems.map((item) => ({
    ...item,
    monthlyValues: monthlyValues(0),
  })),
};
